import type {
  ClassificationResult,
  Classifier,
  ClassifierConfig,
  ClassifierRegistryInterface,
  ConfidenceRouterDeps,
  ConfusionMatrix,
  DecisionType,
  EvaluationDataset,
  EvaluationMetrics,
  FallbackHandler,
  LabeledExample,
  LanguageConfig,
  LanguageManagerInterface,
  OptimizedThresholds,
  Prediction,
  PromptGeneratorInterface,
  RouterConfig,
  RouterInterface,
  RoutingDecision,
} from './types/index.js';

export { DEFAULT_CONFIG, mergeConfig, validateConfig } from './config/index.js';
export { DecisionEngine } from './DecisionEngine.js';
export { RouterError, RouterErrorType } from './types/errors.js';
export type {
  ClassificationResult,
  Classifier,
  ClassifierConfig,
  ClassifierRegistryInterface,
  ConfidenceRouterDeps,
  ConfusionMatrix,
  DecisionType,
  EvaluationDataset,
  EvaluationMetrics,
  FallbackHandler,
  LabeledExample,
  LanguageConfig,
  LanguageManagerInterface,
  OptimizedThresholds,
  Prediction,
  PromptGeneratorInterface,
  RouterConfig,
  RouterInterface,
  RoutingDecision,
};
